language: python
python:
    - "3.5"
    - "3.5-dev"
    - "nightly"
before_install:
    - "pip install coveralls"
    - "pip install coverage"
install: 
    - "pip install ."
script:  "nosetests --with-coverage -v"
after_success:
    - coveralls
